### ISSUE TITLE
some stuff missing

### ISSUE THREAD

**Issue by ThomasWaldmann** [adamgreen/LYWSD02#3]
See there: https://github.com/adamgreen/LYWSD02/community

While some of that might be overkill for a small project like this, guess it should have in any case:
- a LICENSE (MIT or BSD license are very liberal) - without that it would have to be considered as copyrighted, non-free code in some jurisdictions
- a README (which will be rendered on the github main page)

**Comment by adamgreen** [comment]
This was something that I just threw together the night I got the sensor so I never cared about it enough to write a README but if someone else found it useful then that was great.

The copyright notice and license is indicated at the top of each source file, (GPL v2). I have pushed up a commit to make this clearer via the LICENSE file.
